file_name:
  initial_states: 'sample_initial_states.csv'
  mesh_network: 'sample_time_data_transfer.csv'
  true_states: 'sample_sat_states_lvlh_all_dist.csv'

time:
  total_simulation: 1000
  delta_runge_kutta: 1.0
  display_period: 10
  estimation:
    b_use_mesh_network_simulator_output: true
    period: 1.0

dynamics:
  dimension: 3
  disturbance_sigma: [0, 0, 0]
  hill: 
    angular_rate: 1.107E-03

network:
  range_threshold:
    range_measurement: 10000
    angle_measurement: 10000
    communication: 1500

sensor:
  range:
    noise_sigma: 0.10
  angle:
    noise_sigma: [0.01, 0.01]
    # 30 arcsec
    # noise_sigma: [0.0001454, 0.0001454]

true_states:
  b_read_from_csv: true

reference_agent:
  initial_state:
    position: [0, 0, 0]
    velocity: [0, 0, 0]

initial_estimate:
  sigma_position: 10.0
  sigma_velocity: 0.1

estimators:
  initial_covariance:
    sigma_position: 100.0
    sigma_velocity: 1.0
  b_use:
    centralized_extended_information_filter: true
    decentralized_extended_information_filter: false
  deif:
    wait_steps: 1
  process_noise:
    sigma_position: 0.01
    sigma_velocity: 0.001