file_name:
  initial_states: 'test.csv'
  mesh_network: 'time_data_transfer.csv'

time:
  total_simulation: 100
  delta_runge_kutta: 0.1
  display_period: 1.0

dynamics:
  dimension: 3
  disturbance_sigma: [0, 0, 0]
  hill: 
    angular_rate: 1.107E-03

network:
  range_threshold:
    range_measurement: 10000
    angle_measurement: 10000
    communication: 1500

sensor:
  range:
    noise_sigma: 0.10
  angle:
    noise_sigma: [0.05, 0.05]

reference_agent:
  initial_state:
    position: [0, 0, 0]
    velocity: [0, 0, 0]

initial_estimate:
  sigma_position: 10
  sigma_velocity: 0.1

estimators:
  initial_covariance:
    sigma_position: 100
    sigma_velocity: 10