file_name:
  initial_states: 'test.csv'
  mesh_network: 'time_data_transfer.csv'

time:
  total_simulation: 30
  delta_runge_kutta: 1
  display_period: 10.0

dynamics:
  dimension: 3
  disturbance_sigma: [0, 0, 0]
  hill: 
    angular_rate: 1.107E-03

network:
  range_threshold: 1500

reference_agent:
  initial_state:
    position: [0, 0, 0]
    velocity: [0, 0, 0]

initial_estimate:
  sigma_position: 100
  sigma_velocity: 1.0